kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - pip install build tempdir
      - python3 -m build
      - ./manage.py test